"""User-facing summary feedback after automatic context compression.

Parses the structured handoff summary generated by ContextCompressor and
produces a short, human-readable recap (goal, progress, state, files,
remaining work) suitable for status callbacks on all platforms.

No LLM call is made here — everything is extracted by code from the existing
structured summary sections.
"""

from __future__ import annotations

import logging
import re
from typing import Any, Dict, List, Optional
from weakref import WeakKeyDictionary

from agent.context_compressor import (
    SUMMARY_PREFIX,
    LEGACY_SUMMARY_PREFIX,
    _HISTORICAL_SUMMARY_PREFIXES,
    _SUMMARY_END_MARKER,
)

logger = logging.getLogger(__name__)


_SECTION_RE = re.compile(r"^##\s+(.+?)\s*$", re.MULTILINE)

# Section titles are normalized by stripping "Historical " and lower-casing.
# This maps the headings ContextCompressor emits to stable lookup keys.
_SECTION_KEY_ALIASES: Dict[str, str] = {
    "task snapshot": "task",
    "in-progress state": "in_progress",
    "pending user asks": "pending",
    "remaining work": "remaining",
}


def _normalize_section_key(title: str) -> str:
    key = title.lower().strip()
    key = key.removeprefix("historical ")
    return _SECTION_KEY_ALIASES.get(key, key)


def _is_none_like(value: Optional[str]) -> bool:
    if not value:
        return True
    return value.strip().rstrip(".").lower() in {"none", "n/a", "unknown"}


def _first_bullets(text: str, max_items: int = 3, max_chars: int = 400) -> List[str]:
    """Return the first non-empty list items from a markdown section."""
    if not text:
        return []
    items: List[str] = []
    for raw_line in text.splitlines():
        line = raw_line.strip()
        if not line:
            continue
        # Strip leading list markers like "1.", "-", "*".
        line = re.sub(r"^\s*(?:\d+\.|[-*])\s+", "", line).strip()
        if _is_none_like(line):
            continue
        # Avoid duplicating the active task if it leaked into completed actions.
        if line.lower().startswith("user asked:"):
            line = line[len("user asked:") :].strip()
        if line:
            items.append(line)
        if len(items) >= max_items:
            break

    # Truncate individual items so one monster bullet cannot consume the
    # whole budget, then cap the total length across all items.
    per_item_budget = max(80, max_chars // max_items)
    truncated: List[str] = []
    total = 0
    for item in items:
        budget = max_chars - total - 3 * len(truncated)
        if budget <= 0:
            break
        # First cap the single item, then respect the remaining total budget.
        if len(item) > per_item_budget:
            item = item[: per_item_budget - 1].rstrip() + "…"
        if len(item) > budget:
            item = item[: budget - 1].rstrip() + "…"
        truncated.append(item)
        total += len(item)
    return truncated


def _first_line(text: Optional[str], max_chars: int = 200) -> str:
    """Return the first non-empty line, truncated."""
    if not text:
        return ""
    for raw_line in text.splitlines():
        line = raw_line.strip()
        if line and not _is_none_like(line):
            if len(line) > max_chars:
                line = line[: max_chars - 1].rstrip() + "…"
            return line
    return ""


def _first_lines(text: Optional[str], max_lines: int = 2, max_chars: int = 240) -> str:
    """Return the first few non-empty lines joined by a separator."""
    if not text:
        return ""
    lines: List[str] = []
    for raw_line in text.splitlines():
        line = raw_line.strip()
        if line and not _is_none_like(line):
            lines.append(line)
            if len(lines) >= max_lines:
                break
    joined = " · ".join(lines)
    if len(joined) > max_chars:
        joined = joined[: max_chars - 1].rstrip() + "…"
    return joined


def _strip_summary_prefix(summary: str) -> str:
    """Return summary body without the current, legacy, or any historical
    handoff prefix, plus the trailing end marker.

    This is a local copy of the logic in ``ContextCompressor`` so the owner
    module does not depend on upstream private method names.
    """
    text = (summary or "").strip()
    for prefix in (SUMMARY_PREFIX, LEGACY_SUMMARY_PREFIX, *_HISTORICAL_SUMMARY_PREFIXES):
        if text.startswith(prefix):
            text = text[len(prefix):].lstrip()
            break
    if text.endswith(_SUMMARY_END_MARKER):
        text = text[: -len(_SUMMARY_END_MARKER)].rstrip()
    return text


def _parse_summary_sections(summary_text: str) -> Dict[str, str]:
    """Split a structured handoff summary into section title → content."""
    text = _strip_summary_prefix(summary_text)
    sections: Dict[str, str] = {}
    matches = list(_SECTION_RE.finditer(text))
    for i, match in enumerate(matches):
        title = match.group(1).strip()
        start = match.end()
        end = matches[i + 1].start() if i + 1 < len(matches) else len(text)
        content = text[start:end].strip()
        key = _normalize_section_key(title)
        sections[key] = content
    return sections


def summarize_compression_feedback(
    summary_text: str,
    before_count: int,
    after_count: int,
    compression_count: int = 1,
    before_tokens: Optional[int] = None,
    after_tokens: Optional[int] = None,
) -> Dict[str, Any]:
    """Return a concise user-facing summary of a completed compression.

    Args:
        summary_text: The raw structured handoff summary (with or without
            the ContextCompressor prefix).
        before_count: Number of messages before compression.
        after_count: Number of messages after compression.
        compression_count: How many times this session has been compressed.
        before_tokens: Optional rough token estimate before compression.
        after_tokens: Optional rough token estimate after compression.

    Returns:
        Dict with ``headline``, ``text`` (platform-agnostic fallback), and
        structured fields for future card builders (``task``, ``completed``,
        ``state``, ``files``, ``next``).
    """
    sections = _parse_summary_sections(summary_text)

    task = _first_line(sections.get("task"), max_chars=220)
    # Strip the literal "User asked:" wrapper and surrounding quotes that the
    # compressor adds to the task snapshot; users should see their ask, not the
    # machine prompt.
    if task.startswith("User asked:"):
        task = task[len("User asked:"):].strip()
    task = task.strip("'\"")

    goal = _first_line(sections.get("goal"), max_chars=220)
    completed = sections.get("completed actions", "")
    active = sections.get("active state", "")
    in_progress = sections.get("in_progress", "")
    blocked = sections.get("blocked", "")
    pending = sections.get("pending", "")
    remaining = sections.get("remaining", "")
    files = sections.get("relevant files", "")

    active_task = task or goal

    completed_bullets = _first_bullets(completed, max_items=3, max_chars=450)
    file_bullets = _first_bullets(files, max_items=4, max_chars=250)

    state_parts: List[str] = []
    active_line = _first_lines(active, max_lines=3, max_chars=220)
    if active_line:
        # Label the active-state line so it matches the other rows instead of
        # floating as a bare, unlabelled line.
        state_parts.append(f"**状态**：{active_line}")
    in_progress_line = _first_line(in_progress, max_chars=120)
    if in_progress_line:
        state_parts.append(f"**进行中**：{in_progress_line}")
    blocked_line = _first_line(blocked, max_chars=120)
    if blocked_line:
        state_parts.append(f"**阻塞**：{blocked_line}")

    next_parts: List[str] = []
    pending_line = _first_line(pending, max_chars=120)
    if pending_line:
        next_parts.append(f"**待处理**：{pending_line}")
    remaining_line = _first_line(remaining, max_chars=120)
    if remaining_line:
        next_parts.append(f"**剩余工作**：{remaining_line}")

    if before_count > 0 and after_count < before_count:
        saved_pct = int((before_count - after_count) / before_count * 100)
    else:
        saved_pct = 0

    token_segment = ""
    if before_tokens is not None and after_tokens is not None:
        token_segment = f" · ~{before_tokens:,} → ~{after_tokens:,} tokens"

    headline = (
        f"🗜️ 上下文已压缩：{before_count} → {after_count} "
        f"条消息（缩短 {saved_pct}%）{token_segment}"
    )
    if compression_count > 1:
        headline += f" · 第 {compression_count} 次"

    body_lines: List[str] = [headline]
    if active_task:
        body_lines.append(f"**任务**：{active_task}")
    if completed_bullets:
        body_lines.append("**进度**：\n" + "\n".join(f"• {b}" for b in completed_bullets))
    if state_parts:
        # One row per line. Joining with a newline (not an inline separator)
        # keeps the Feishu card builder dumb — it never has to split a line and
        # so can never mangle content that legitimately contains the separator.
        body_lines.append("\n".join(state_parts))
    if file_bullets:
        body_lines.append("**文件**：" + ", ".join(file_bullets))
    if next_parts:
        body_lines.append("\n".join(next_parts))

    return {
        "headline": headline,
        "text": "\n\n".join(body_lines),
        "task": active_task,
        "completed": completed_bullets,
        "state": " · ".join(state_parts),
        "files": file_bullets,
        "next": " · ".join(next_parts),
    }


def summarize_compression_fallback(
    before_count: int,
    after_count: int,
    compression_count: int = 1,
    before_tokens: Optional[int] = None,
    after_tokens: Optional[int] = None,
) -> Dict[str, Any]:
    """Plain fallback when no structured summary is available (e.g. summary failed).

    Returns the same shape as ``summarize_compression_feedback`` but without
    content-derived fields.
    """
    if before_count > 0 and after_count < before_count:
        saved_pct = int((before_count - after_count) / before_count * 100)
    else:
        saved_pct = 0

    token_segment = ""
    if before_tokens is not None and after_tokens is not None:
        token_segment = f" · ~{before_tokens:,} → ~{after_tokens:,} tokens"

    headline = (
        f"🗜️ 上下文已压缩：{before_count} → {after_count} "
        f"条消息（缩短 {saved_pct}%）{token_segment}"
    )
    if compression_count > 1:
        headline += f" · 第 {compression_count} 次"

    return {
        "headline": headline,
        "text": headline,
        "task": "",
        "completed": [],
        "state": "",
        "files": [],
        "next": "",
    }


# External state for the last display summary per compressor instance.
# We key by the compressor object itself in a WeakKeyDictionary so entries are
# dropped automatically when the compressor is garbage collected. This avoids
# a slow memory leak in long-running gateway processes where each session may
# create a fresh AIAgent/ContextCompressor pair, and it keeps the upstream
# ContextCompressor lifecycle untouched.
_last_display_summary: WeakKeyDictionary[Any, str] = WeakKeyDictionary()


def set_last_summary(compressor: Any, summary: str) -> None:
    """Store the raw handoff summary for a compressor instance."""
    _last_display_summary[compressor] = summary


def get_last_summary(compressor: Any) -> Optional[str]:
    """Return the raw handoff summary stored for a compressor instance."""
    return _last_display_summary.get(compressor)


def clear_last_summary(compressor: Any) -> None:
    """Drop stored summary for a compressor instance.

    Currently used as defense-in-depth; callers may invoke this when a
    compressor/session is explicitly destroyed to release the stored summary
    immediately rather than waiting for garbage collection.
    """
    _last_display_summary.pop(compressor, None)


def emit_compression_summary(
    agent,
    before_count: int,
    after_count: int,
    before_tokens: Optional[int] = None,
    after_tokens: Optional[int] = None,
) -> None:
    """Emit a concise user-facing summary after context compression.

    This is a platform-agnostic lifecycle status; rich platforms (e.g. Feishu)
    can detect the emitted text and render an interactive card.
    """
    compressor = getattr(agent, "context_compressor", None)
    summary_for_display = get_last_summary(compressor) or "" if compressor else ""

    if summary_for_display:
        feedback = summarize_compression_feedback(
            summary_text=summary_for_display,
            before_count=before_count,
            after_count=after_count,
            compression_count=getattr(compressor, "compression_count", 1) if compressor else 1,
            before_tokens=before_tokens,
            after_tokens=after_tokens,
        )
    else:
        feedback = summarize_compression_fallback(
            before_count=before_count,
            after_count=after_count,
            compression_count=getattr(compressor, "compression_count", 1) if compressor else 1,
            before_tokens=before_tokens,
            after_tokens=after_tokens,
        )

    emit = getattr(agent, "_emit_status", None)
    if emit is None:
        return
    try:
        emit(feedback["text"])
    except Exception:
        logger.debug("Failed to emit compression feedback summary", exc_info=True)


__all__ = [
    "summarize_compression_feedback",
    "summarize_compression_fallback",
    "set_last_summary",
    "get_last_summary",
    "clear_last_summary",
    "emit_compression_summary",
]
