"""Chinese tip translations for the random tip display.

   Loaded by ``hermes_cli/tips.py::get_random_tip()`` when
   ``HERMES_LANGUAGE`` starts with ``zh``.

   可移除性：删除此文件后，中文环境用户回退到英文 tips，
   功能不受影响。
   """

from __future__ import annotations

TIPS = [
    # --- Slash Commands ---
    "/background <prompt>（别名 /bg 或 /btw）在独立 session 中运行任务，当前对话保持空闲。",
    "/branch 分叉当前会话，让你在不丢失进度的情况下探索不同方向。",
    "/compress 手动压缩对话上下文，内容过长时使用。",
    "/rollback 列出文件系统检查点 — 将 agent 修改过的文件恢复到任意之前的状态。",
    "/rollback diff 2 预览自检查点 2 以来的变更，不实际恢复。",
    "/rollback 2 src/file.py 从指定检查点恢复单个文件。",
    '/title "my project" 为会话命名 — 之后可用 /resume 或 hermes -c 继续。',
    "/resume 继续之前命名的会话。",
    "/queue <prompt> 将消息排队到下一轮，不打断当前执行。",
    "/undo 删除最后一轮用户/助手交互。",
    "/retry 重发你的最后一条消息 — 当 agent 的回复不够好时使用。",
    "/verbose 循环切换工具进度显示模式：off → new → all → verbose。",
    "/reasoning high 提高模型的思考深度。/reasoning show 显示推理过程。",
    "/fast 切换优先处理模式，获取更快的 API 响应（取决于 provider）。",
    "/yolo 跳过本会话中所有危险命令审批提示。",
    "/model 让你中途切换模型 — 试试 /model sonnet 或 /model gpt-5。",
    "/model --global 永久更改默认模型。",
    "/personality pirate 设置趣味人格 — 14 种内置选项，从 kawaii 到 shakespeare。",
    "/skin 更换 CLI 主题 — 试试 ares、mono、slate、poseidon 或 charizard。",
    "/statusbar 切换持久状态栏，显示模型、token、上下文填充率、费用和时长。",
    "/tools disable browser 临时移除当前会话的 browser 工具。",
    "/browser connect 通过 CDP 将 browser 工具连接到你正在运行的 Chromium 系列 browser。",
    "/plugins 列出已安装的插件及其状态。",
    "/cron 管理定时任务 — 设置循环提示，可投递到任意平台。",
    "/reload-mcp 热重载 MCP 服务器配置，无需重启。",
    "/usage 显示 token 用量、费用明细和会话时长。",
    "/insights 显示最近 30 天的使用分析。",
    "/paste 检查剪贴板中的图片并附加到下一条消息。",
    "/profile 显示当前活跃的 profile 名称及其 home 目录。",
    "/config 显示当前配置概览。",
    "/stop 终止 agent 启动的所有后台进程。",

    # --- @ Context References ---
    "@file:path/to/file.py 将文件内容直接注入你的消息。",
    "@file:main.py:10-50 只注入文件的第 10-50 行。",
    "@folder:src/ 注入目录树列表。",
    "@diff 注入你未暂存的 git 变更。",
    "@staged 注入你已暂存的 git 变更（git diff --staged）。",
    "@git:5 注入最近 5 条提交及其完整补丁。",
    "@url:https://example.com 获取并注入网页内容。",
    "输入 @ 触发文件系统路径补全 — 交互式导航到任意文件。",
    '可以组合多个引用："Review @file:main.py and @file:test.py for consistency."',

    # --- Keybindings ---
    "Alt+Enter 插入换行，用于多行输入。（Windows Terminal 会拦截 Alt+Enter — 改用 Ctrl+Enter。）",
    "Ctrl+C 中断 agent。2 秒内双击强制退出。",
    "Ctrl+Z 将 Hermes 挂起到后台 — 在 shell 中运行 fg 恢复。",
    "Tab 接受自动建议的幽灵文本或补全 slash 命令。",
    "在 agent 工作时输入新消息可以中断并重定向。",
    "Alt+V 从剪贴板粘贴图片到对话中。",
    "粘贴 5 行以上内容会自动保存到文件，并插入紧凑引用。",

    # --- CLI Flags ---
    'hermes -c 继续最近的 CLI 会话。hermes -c "project name" 按标题继续。',
    "hermes -w 创建一个隔离的 git worktree — 适合并行 agent 工作流。",
    'hermes -w -q "Fix issue #42" 组合 worktree 隔离和一次性查询。',
    "hermes chat -t web,terminal 只启用特定 toolset 的专注会话。",
    "hermes chat -s github-pr-workflow 启动时预加载 skill。",
    'hermes chat -q "query" 运行单次非交互查询后退出。',
    "hermes chat --max-turns 200 覆盖默认的每轮 90 次迭代限制。",
    "hermes chat --checkpoints 启用文件系统检查点实现可撤销的破坏性变更。",
    "hermes --yolo 跳过整个会话的所有危险命令审批提示。",
    "hermes chat --source telegram 为会话打标签，方便在 hermes sessions list 中筛选。",
    "hermes -p work chat 在指定 profile 下运行，不改变默认配置。",
    "/reasoning low 或 /reasoning minimal 将思考深度降到默认(medium)以下 — 更快更省。",

    # --- CLI Subcommands ---
    "hermes doctor --fix 诊断并自动修复配置和依赖问题。",
    "hermes dump 输出精简的配置摘要 — 适合写 bug 报告。",
    "hermes config set KEY VALUE 自动将密钥路由到 .env，其余写入 config.yaml。",
    "hermes config edit 在默认编辑器中打开 config.yaml。",
    "hermes config check 扫描缺失或过期的配置项。",
    "hermes sessions browse 打开带搜索的交互式会话选择器。",
    "hermes sessions stats 显示会话数和数据库大小，按平台分组。",
    "hermes sessions prune --older-than 30 清理旧会话。",
    "hermes skills search react --source skills-sh 搜索 skills.sh 公共目录。",
    "hermes skills check 扫描已安装的 hub skill 是否有上游更新。",
    "hermes skills tap add myorg/skills-repo 添加自定义 GitHub skill 来源。",
    "hermes mcp add github --command npx 从命令行添加 MCP 服务器。",
    "hermes mcp serve 将 Hermes 自身作为 MCP 服务器供其他 agent 使用。",
    "hermes auth add 让你添加多个 API key 用于凭证池轮换。",
    "hermes completion bash >> ~/.bashrc 为所有命令和 profile 启用 tab 补全。",
    "hermes logs -f 实时跟踪 agent.log。--level WARNING --since 1h 过滤输出。",
    "hermes backup 创建整个 Hermes home 目录的 zip 备份。",
    "hermes profile create coder 创建隔离的 profile，它会成为独立的命令。",
    "hermes profile create work --clone 将当前配置和密钥复制到新 profile。",
    "hermes update 自动将新的内置 skill 同步到所有 profile。",
    "hermes gateway install 将 Hermes 安装为系统服务（systemd/launchd）。",
    "hermes memory setup 让你配置外部 memory provider（Honcho、Mem0 等）。",
    "hermes webhook subscribe 创建带 HMAC 验证的事件驱动 webhook 路由。",
    "省钱技巧：hermes tools 禁用不用的工具，hermes skills config 精简 skill 列表。",

    # --- Configuration ---
    "在 config.yaml 中设置 display.bell_on_complete: true，长任务完成时响铃。",
    "设置 display.streaming: true 实时查看模型生成 token。",
    "设置 display.show_reasoning: true 观看模型的思维链推理。",
    "设置 display.compact: true 减少输出空白，信息更紧凑。",
    "设置 display.busy_input_mode: queue 排队消息而非中断 agent。",
    "设置 display.resume_display: minimal 恢复会话时跳过完整对话回顾。",
    "设置 compression.threshold: 0.50 控制自动压缩触发时机（默认：上下文 50%）。",
    "设置 agent.max_turns: 200 让 agent 每轮执行更多工具调用步骤。",
    "设置 file_read_max_chars: 200000 增加每次 read_file 调用的最大内容量。",
    "设置 approvals.mode: smart 让 LLM 自动批准安全命令、自动拒绝危险命令。",
    "在 config.yaml 中设置 fallback_model 自动故障转移到备用 provider。",
    "设置 privacy.redact_pii: true 在发送给 LLM 之前哈希用户 ID 和电话号码。",
    "设置 browser.record_sessions: true 自动将 browser 会话录制为 WebM 视频。",
    "在 config.yaml 中设置 worktree: true 始终创建 git worktree。",
    "设置 security.website_blocklist.enabled: true 阻止 web 工具访问指定域名。",
    "设置 cron.wrap_response: false 投递原始 agent 输出，不带 cron 头尾。",
    "HERMES_TIMEZONE 用任意 IANA 时区字符串覆盖服务器时区。",
    "config.yaml 支持环境变量替换：使用 ${VAR_NAME} 语法。",
    "config.yaml 中的 Quick commands 无需 token 即可即时运行 shell 命令。",

    # --- Tools & Capabilities ---
    "execute_code 运行可编程调用 Hermes 工具的 Python 脚本 — 结果不进入上下文。",
    "delegate_task 生成最多 3 个并发 sub-agent，各拥有隔离上下文用于并行工作。",
    "web_extract 支持 PDF URL — 传入任何 PDF 链接即可转换为 markdown。",
    "search_files 基于 ripgrep，比 grep 更快 — 用它代替终端 grep。",
    "patch 使用 9 种模糊匹配策略，轻微空白差异不会导致编辑失败。",
    "patch 支持 V4A 格式，单次调用即可批量编辑多个文件。",
    "read_file 在文件找不到时会建议相似文件名。",
    "read_file 自动去重 — 重新读取未变更的文件返回轻量占位。",
    "browser_vision 截图并用 AI 分析 — 适用于 CAPTCHA 和视觉内容。",
    "browser_console 可以在页面上下文中执行 JavaScript 表达式。",
    "image_generate 使用 FLUX 2 Pro 创建图片，自动 2x 放大。",
    "text_to_speech 将文字转语音 — 在 Telegram 上以语音气泡播放。",
    "send_message 可以在会话中向任何已连接的消息平台发送消息。",
    "todo 工具帮助 agent 在会话中追踪复杂的多步骤任务。",
    "session_search 对所有历史对话执行全文搜索。",
    "agent 自动将偏好、纠正和环境信息保存到 memory。",
    "mixture_of_agents 将难题路由给 4 个前沿 LLM 协作处理。",
    "Terminal 命令支持后台模式，配合 notify_on_complete 处理长时间运行的任务。",
    "Terminal 后台进程支持 watch_patterns，在特定输出行出现时提醒。",
    "terminal 工具支持 6 种后端：local、Docker、SSH、Modal、Daytona 和 Singularity。",

    # --- Security ---
    "危险命令审批有 4 个等级：once、session、always（永久白名单）、deny。",
    "Smart 审批模式使用 LLM 自动批准安全命令并标记危险命令。",
    "SSRF 防护阻止私有网络、回环地址、链路本地和云元数据地址。",
    '上下文文件（.hermes.md、AGENTS.md）在加载前会进行安全扫描，检测 prompt 注入。',

    # --- Advanced ---
    "/steer <prompt> 在下一个工具调用后注入提示 — 中途调整方向，不打断执行。",
    "/goal <text> 设置持续目标 — Hermes 每轮自动继续，直到 judge 判定完成。",
    "/copy [N] 将最后一条助手回复复制到剪贴板，加数字则复制倒数第 N 条。",
    "/restart 优雅重启 gateway（等待活跃任务结束），重启后通知请求者。",
    "Cron 任务可以附加 skill 或 Python 脚本。",
    "Profile 名称不能与现有 PATH 二进制冲突。",
    "每位 profile 拥有独立的 config、API key、memory、session、skill 和 cron 任务。",
    "80+ 内置 skill，覆盖 github、creative、mlops、productivity、research 等。",
    "Gateway 钩子位于 ~/.hermes/hooks/<name>/，包含 HOOK.yaml + handler.py。",
    "MCP 服务器在 config.yaml 中配置 — 同时支持 stdio 和 HTTP 传输。",
]
